language: python

sudo: false

addons:
  apt:
    packages:
    - mono-devel

env:
  - LUA="lua 5.1"
  - LUA="lua 5.2"
  - LUA="lua 5.3"
  - LUA="luajit 2.0.4" # version used by Garry's Mod
  - LUA="luajit 2.0"
  - LUA="luajit 2.1"

stages:
  - name: before_deploy
    #if: branch = master AND type != pull_request
    if: env(LUA) = "lua 5.1"
  - name: deploy
    #if: branch = master AND type != pull_request
    if: env(LUA) = "lua 5.1"

install:
  - pip install hererocks
  - hererocks env --$LUA -rlatest    # Use latest LuaRocks, install into 'env' directory.
  - source env/bin/activate          # Add directory with all installed binaries to PATH.
  - luarocks install moonscript
  - luarocks install busted
  - if [ "$LUA" = "lua 5.2" ] || [ "$LUA" = "lua 5.3" ]; then luarocks install lua-cjson 2.1.0-1;
    else luarocks install lua-cjson; fi # Bug in newer rocks for Lua >= 5.2
  - luarocks install luafilesystem

script:
  - make test
  - test $TRAVIS_PULL_REQUEST = false || make check

before_deploy:
  - wget https://www.naturaldocs.org/download/natural_docs/2.0.2/Natural_Docs_2.0.2.zip -O /tmp/ND.zip
  - unzip /tmp/ND.zip -d /tmp
  - mono "/tmp/Natural Docs/NaturalDocs.exe" -r -i . -o HTML doc -p doc/ndinfo

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: ci-tests

notifications:
  recipients:
    - megiddo@ulyssesmod.net
    - sticklyman@ulyssesmod.net
  email:
    on_success: change
    on_failure: always
