# (Mostly) stolen from github.com/moteus/lua-travis-example
language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit     # latest stable version (2.0.3)
    - LUA=luajit2.0  # current head of 2.0 branch
    - LUA=luajit2.1  # current head of 2.1 branch

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install moonscript
  - luarocks install busted
  - luarocks install lua-cjson
  - luarocks install luafilesystem

script:
  - busted tests

notifications:
  recipients:
    - megiddo@ulyssesmod.net
    - sticklyman@ulyssesmod.net
  email:
    on_success: change
    on_failure: always
