# (Mostly) stolen from github.com/Ovine-Labs/busted
language: c

env:
	- LUA='Lua 5.1'
	
before_install:
	- bash .travis_setup.sh

branches:
	only:
		- master

install:
	- sudo apt-get update -qq
	- sudo luarocks install busted
	- sudo luarocks install moonscript

script: busted spec

notifications:
	recipients:
		- megiddo@ulyssesmod.net
		- sticklyman@ulyssesmod.net
	email:
		on_success: always
		on_failure: always
