# (Mostly) stolen from github.com/moteus/lua-travis-example
language: c

sudo: false

env:
  global:
    - LUAROCKS=2.3.0

  matrix:
    include:
      - os: linux
        env: LUA=lua5.1
      - os: osx
        env: LUA=lua5.1
      - os: linux
        env: LUA=lua5.2
      - os: osx
        env: LUA=lua5.2
      - os: linux
        env: LUA=lua5.3
      - os: osx
        env: LUA=lua5.3
      - os: linux
        env: LUA=luajit # Latest stable version
      - os: osx
        env: LUA=luajit # Latest stable version
      - os: linux
        env: LUA=luajit2.0
      - os: osx
        env: LUA=luajit2.0
      - os: linux
        env: LUA=luajit2.1
      - os: osx
        env: LUA=luajit2.1

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh
  - pip install --user cpp-coveralls
  - luarocks install moonscript
  - luarocks install busted
  - luarocks install lua-cjson
  - luarocks install luafilesystem

script:
  - make test
  - test $TRAVIS_PULL_REQUEST = false || make check

notifications:
  recipients:
    - megiddo@ulyssesmod.net
    - sticklyman@ulyssesmod.net
  email:
    on_success: change
    on_failure: always
